// Code generated by github.com/Bin-Huang/newc; DO NOT EDIT.

package rest

import (
	"orders/actions"
	"orders/infra"
)

// NewAddProduct Create a new AddProduct
func NewAddProduct(action *actions.ProductAdder, rspndr *Responder, logger infra.Logger) *AddProduct {
	return &AddProduct{
		action: action,
		rspndr: rspndr,
		logger: logger,
	}
}

// NewConfirmPayment Create a new ConfirmPayment
func NewConfirmPayment(confirmPayment *actions.ConfirmPayment, rspndr *Responder, logger infra.Logger) *ConfirmPayment {
	return &ConfirmPayment{
		confirmPayment: confirmPayment,
		rspndr:         rspndr,
		logger:         logger,
	}
}

// NewCreateOrder Create a new CreateOrder
func NewCreateOrder(action *actions.CreateOrder, rspndr *Responder, logger infra.Logger) *CreateOrder {
	return &CreateOrder{
		action: action,
		rspndr: rspndr,
		logger: logger,
	}
}

// NewDeleteProduct Create a new DeleteProduct
func NewDeleteProduct(action *actions.ProductDeleter, rspndr *Responder, logger infra.Logger) *DeleteProduct {
	return &DeleteProduct{
		action: action,
		rspndr: rspndr,
		logger: logger,
	}
}

// NewRetrieveOrder Create a new RetrieveOrder
func NewRetrieveOrder(action *actions.RetrieveOrder, rspndr *Responder, logger infra.Logger) *RetrieveOrder {
	return &RetrieveOrder{
		action: action,
		rspndr: rspndr,
		logger: logger,
	}
}

// NewCheckoutTransfer Create a new CheckoutTransfer
func NewCheckoutTransfer(retrieve *actions.RetrieveOrder, checkout *actions.CheckoutTransfer, rspndr *Responder, logger infra.Logger) *CheckoutTransfer {
	return &CheckoutTransfer{
		retrieve: retrieve,
		checkout: checkout,
		rspndr:   rspndr,
		logger:   logger,
	}
}
